# cmake -DIN=file -DOUT=file.c -DNAME=sym -P embed.cmake: IN as
# `const unsigned char NAME[]` and `const unsigned int NAME_len` in OUT
# (the port's built-in font, port/fonts/, for --hd-text)
file(READ ${IN} hex HEX)
string(LENGTH "${hex}" n)
math(EXPR len "${n} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
string(REGEX REPLACE "((0x..,){24})" "\\1\n" body "${body}")
file(WRITE ${OUT} "/* generated by port/tools/embed.cmake from ${IN} */\n"
    "const unsigned char ${NAME}[${len} + 1] = {\n${body}0 };\n"
    "const unsigned int ${NAME}_len = ${len};\n")
