#!/usr/bin/env python3
"""The ROM's segments and the type layouts for the port's loaders (host/native.c).

  gen_romtab.py OUT.h

With each one's class (ROM_*: what the loaders convert it as; ROM_BYTES
is texels, samples, code, left as they are).  And, for the types the
loaders convert that the type inventory (blastcorps/include/game/
inventory.json) has, their layouts as field strings (b a byte, h 16 bits,
w 32, d 64: host/native.c's rec()).  From the top-level link map (build/blastcorps.<version>.map, the version
from PORT_VERSION, default us.v11): every `<name>_ROM_START`/`_ROM_END`
pair, as a sorted C table {start, end, name}.  The loaders use it to name
what a PI DMA or an LZSS load brings in; gzip members name themselves.
"""
import json
import os
import re
import sys

# the inventory's types the loaders use (host/native.c)
LAYOUTS = ["VehicleState", "PlayerInfo"]
SCALAR = {"s8": 1, "u8": 1, "s16": 2, "u16": 2, "s32": 4, "u32": 4, "f32": 4, "s64": 8, "u64": 8, "f64": 8,
          "ptr": 4, "romoff": 4, "segptr": 4, "offset": 4, "gfx": 4, "bytes": 1}


def layout(types, name):
    """the type as a field string, gaps as bytes"""
    t = types[name]
    widths = [1] * t["size"]
    starts = [True] * t["size"]

    def put(tname, off):
        if tname in SCALAR:
            w = SCALAR[tname]
            for k in range(w):
                widths[off + k] = w
                starts[off + k] = k == 0
            return
        for f in types[tname]["fields"]:
            size = SCALAR.get(f["type"]) or types[f["type"]]["size"]
            for c in range(f.get("count", 1)):
                put(f["type"], off + f["off"] + c * size)
    put(name, 0)
    out, k = "", 0
    while k < len(widths):
        w = widths[k] if starts[k] else 1
        out += {1: "b", 2: "h", 4: "w", 8: "d"}[w]
        k += w
    return out

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))


def main():
    version = os.environ.get("PORT_VERSION", "us.v11")
    mp = os.path.join(ROOT, "build", f"blastcorps.{version}.map")
    start, end = {}, {}
    for line in open(mp):
        m = re.match(r"\s+0x([0-9a-f]+)\s+(\w+)_ROM_(START|END) = ", line)
        if m:
            (start if m.group(3) == "START" else end)[m.group(2)] = int(m.group(1), 16)
    segs = sorted((start[n], end[n], n) for n in start if n in end and end[n] > start[n])
    names = [n for _, _, n in segs]

    def between(first, last):
        a, b = names.index(first), names.index(last)
        return set(names[a:b + 1])
    # what each segment's data is (host/native.c converts by it); the order is
    # docs/ASSETS.md's, the same in every version
    klass = {}
    for n in between("scientist", "shuttle_dl") | between("usa_star", "reflectlogo_dl"):
        klass[n] = "ROM_VEHICLE"
    for n in between("lagp", "level59_dl"):
        klass[n] = "ROM_LEVEL"
    for n in names[names.index("model_table") + 1:names.index("static_data")]:
        klass[n] = "ROM_MODEL"
    for n in names:
        if n.endswith("_dl") or re.search(r"_dl_[0-9A-F]+$", n):
            klass[n] = "ROM_DL"
    fixed = {"texture_table": "ROM_TEXTURE_TABLE", "model_table": "ROM_MODEL_TABLE",
             "music_ctl": "ROM_BANK", "sfx_ctl": "ROM_BANK", "sequences": "ROM_SEQUENCES",
             "static_data": "ROM_STATIC", "attract": "ROM_ATTRACT"}
    klass.update(fixed)
    with open(sys.argv[1], "w") as f:
        f.write(f"/* generated by port/tools/gen_romtab.py from {os.path.basename(mp)} */\n")
        f.write("static const struct rom_segment { uint32_t start, end; const char *name; int klass; } rom_segments[] = {\n")
        for s, e, n in segs:
            f.write(f'    {{0x{s:06X}, 0x{e:06X}, "{n}", {klass.get(n, "ROM_BYTES")}}},\n')
        f.write("};\n")
        inv = json.load(open(os.path.join(ROOT, "blastcorps", "include", "game", "inventory.json")))
        for name in LAYOUTS:
            f.write(f'static const char layout_{name}[] = "{layout(inv["types"], name)}";\n')


if __name__ == "__main__":
    main()
