#!/usr/bin/env python3
"""Symbols for the port's link, and the addresses the translated code uses.

  gen_syms.py header OUT.h
      For the translated code: SYM_<name> as the address of the native
      symbol, for every name the generated syms_<module>.h lists (functions
      of the translated code itself excepted; only funcs.c's table uses
      those, and the port doesn't build it).

  gen_syms.py script OUT.ld OBJECT...
      For the linker: every name the N64 link gets from a linker script
      (build/<module>.<version>.syms.ld, the ROM positions) that no object of
      the port defines.  Names inside another variable or a data island
      stay relative to it (`D_X = base + off`); fixed addresses (the
      libultra globals at 0x80000300, hardware registers, RDRAM buffers)
      stay absolute, which works because RDRAM is mapped at 0x80000000.
      A name relative to something the port doesn't define (libultra
      internals it replaces) falls back to its N64 address.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
BLAST = os.path.join(ROOT, "blastcorps")
# the version of the stage-2 build the port is made from (CMake sets it)
VERSION = os.environ.get("PORT_VERSION", "us.v11")
GEN = os.path.join(BLAST, "build", "recomp", "src")
MODULES = ("hd_code", "hd_front_end")

ASSIGN_RE = re.compile(r"^\s*([A-Za-z_][\w.]*)\s*=\s*([^;]+);\s*(?:/\*\s*(.*?)\s*\*/)?")
REL_COMMENT_RE = re.compile(r"^([A-Za-z_]\w*)\s*\+\s*(0x[0-9A-Fa-f]+)\s+in\s+(\w+)")


def recomp_funcs():
    return set(re.findall(r"recomp_(func_[0-9A-F]{8})\(", open(os.path.join(GEN, "recomp_funcs.h")).read()))


def header(out):
    names = set()
    for m in MODULES:
        p = os.path.join(GEN, f"syms_{m}.h")
        names |= set(re.findall(r"#ifndef SYM_(\w+)", open(p).read()))
    skip = recomp_funcs()
    with open(out, "w") as f:
        f.write("/* Generated by port/tools/gen_syms.py: the translated code's addresses\n"
                "   are those of the port's own symbols. */\n#include <stdint.h>\n")
        for n in sorted(names - skip):
            f.write(f"extern char port_sym_{n}[] __asm__(\"{n}\");\n"
                    f"#define SYM_{n} ((uint32_t)(uintptr_t)port_sym_{n})\n")


def n64_addresses():
    addrs = {}
    for m in MODULES + ("init",):
        elf = os.path.join(BLAST, "build", f"{m}.{VERSION}.elf")
        out = subprocess.run(["mips-linux-gnu-nm", elf], capture_output=True, text=True, check=True).stdout
        for line in out.splitlines():
            p = line.split()
            if len(p) == 3:
                addrs.setdefault(p[2], int(p[0], 16))
    return addrs


def script(out, objects):
    defined = set()
    objs = [o for arg in objects for o in arg.split(";") if o]
    for k in range(0, len(objs), 200):
        res = subprocess.run(["nm", "-P", "--defined-only"] + objs[k:k + 200],
                             capture_output=True, text=True, check=True).stdout
        for line in res.splitlines():
            p = line.split()
            if len(p) >= 2 and not p[0].endswith(":"):
                defined.add(p[0])
    n64 = n64_addresses()
    assigns = {}
    order = []
    srcs = [os.path.join(BLAST, "build", f"{m}.{VERSION}.syms.ld") for m in MODULES]
    srcs.append(os.path.join(BLAST, "build", f"rom_fixed.{VERSION}.ld"))
    for src in srcs:
        for line in open(src):
            m = ASSIGN_RE.match(line)
            if not m:
                continue
            name, rhs, comment = m.group(1), m.group(2).strip(), m.group(3)
            if name in defined or name in assigns:
                continue
            if name == "D_803FF600":
                continue        # port_fixed.ld.in
            if comment:
                c = REL_COMMENT_RE.match(comment)
                if c:
                    if c.group(1) == name:
                        continue        # the port defines it, or doesn't need it
                    rhs = f"{c.group(1)} + {c.group(2)}"
                else:
                    rm = re.match(r"originally (0x[0-9A-Fa-f]+)", comment)
                    if rm:
                        rhs = rm.group(1)     # ROM offsets of the original ROM
            assigns[name] = rhs
            order.append(name)

    def resolve(name, depth=0):
        """RHS usable in the port: base symbols must exist."""
        rhs = assigns[name]
        # the game's data is at its N64 addresses (gen_ld.py), so anything
        # in RDRAM the port doesn't define is simply there
        if name in n64 and 0x80000000 <= n64[name] < 0x80400000 and not name.startswith("func_"):
            return f"0x{n64[name]:08X}"
        m = re.match(r"^([A-Za-z_]\w*)\s*\+\s*(0x[0-9A-Fa-f]+|\d+)$", rhs)
        if not m:
            m2 = re.match(r"^([A-Za-z_]\w*)$", rhs)
            if m2:
                base = m2.group(1)
                if base in defined or (base in assigns and depth < 8):
                    return rhs
                if name in n64:
                    return f"0x{n64[name]:08X}"
                return None
            return rhs
        base = m.group(1)
        if base in defined or base in assigns:
            return rhs
        if name in n64:
            return f"0x{n64[name]:08X}"
        return None

    with open(out, "w") as f:
        f.write("/* Generated by port/tools/gen_syms.py; see there. */\n")
        for name in order:
            rhs = resolve(name)
            if rhs is None:
                f.write(f"/* {name}: no base for {assigns[name]} */\n")
                continue
            f.write(f"{name} = {rhs};\n")


def main():
    if sys.argv[1] == "header":
        header(sys.argv[2])
    elif sys.argv[1] == "script":
        script(sys.argv[2], sys.argv[3:])
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
