#!/usr/bin/env python3
"""Write sins()'s quarter-wave table (port/src/gu.c) as a C header.

    gen_sintable.py OUT.h

Entry i of the 1,024 is trunc(32767 sin(i pi / 2046)), in s1.15, so the last
one is sin(pi/2) = 32767.  Every value is at least 1e-4 from the next whole
number, so any libm's sin gives the same table.
"""
import math
import sys

vals = [int(32767 * math.sin(i * math.pi / 2046)) for i in range(1024)]
with open(sys.argv[1], "w") as f:
    f.write("/* generated by port/tools/gen_sintable.py */\n")
    f.write("static const s16 port_sintable[1024] = {\n")
    for i in range(0, 1024, 8):
        f.write("    " + " ".join(f"{v}," for v in vals[i:i + 8]) + "\n")
    f.write("};\n")
