#!/usr/bin/env python3
"""Place the game's data at its N64 addresses.

  gen_ld.py script OUT.ld OBJECT...    the linker script
  gen_ld.py check EXE                  after the link: every game data
                                       symbol at its N64 address?

The decompiled C (and the handwritten code) rely on the layout of the
data: a struct read past the end of one variable into the next, fixed
RDRAM addresses, the heap starting where hd_code's .bss ends.  So the port
keeps every variable where the N64 has it.  The game's C is built with
-fdata-sections (one section per variable, `.data.NAME`, `.bss.NAME`), and
so is the handwritten objects' data, which tools/asm2c.py writes as C.
The script puts all of them in one output section, `.rdram`, at
0x80000000, each at its symbol's address in the N64 link; the section is
the 4 MB of RDRAM, so it also replaces a separate arena.  Sections of
variables with no N64 symbol (literals, statics the N64 build doesn't
name, the port's own data) go wherever the host linker puts them.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
BLAST = os.path.join(ROOT, "blastcorps")
# the version of the stage-2 build the port is made from (CMake sets it)
VERSION = os.environ.get("PORT_VERSION", "us.v11")
RDRAM = 0x80000000
RDRAM_END = 0x80400000


def n64_symbols(sizes=None):
    addrs = {}
    for m in ("hd_code", "hd_front_end"):
        elf = os.path.join(BLAST, "build", f"{m}.{VERSION}.elf")
        out = subprocess.run(["mips-linux-gnu-nm", "-S", elf], capture_output=True, text=True, check=True).stdout
        for line in out.splitlines():
            p = line.split()
            if len(p) == 4:
                p = [p[0], p[2], p[3], p[1]]
            if len(p) >= 3 and not p[2].startswith((".L", "$")):
                addrs.setdefault(p[2], int(p[0], 16))
                if sizes is not None and len(p) == 4:
                    sizes.setdefault(p[2], int(p[3], 16))
    return addrs


SEC_RE = re.compile(r"^\s*\[\s*\d+\]\s+(\S+)\s+(PROGBITS|NOBITS)\s+\S+\s+\S+\s+([0-9a-f]+)\s+\S+\s+\S*\s+\d+\s+\d+\s+(\d+)")
# the LP64 build (docs/PORT.md, "The LP64 build"): a variable of a type the
# host lays out bigger than the N64 does can't stay where the N64 has it
LP64 = os.environ.get("PORT_LP64") == "1"


def sections(obj):
    """(name, size, alignment) of every non-empty data section"""
    out = subprocess.run(["readelf", "-SW", obj], capture_output=True, text=True, check=True).stdout
    res = []
    for line in out.splitlines():
        m = SEC_RE.match(line)
        if m and int(m.group(3), 16) > 0:
            res.append((m.group(1), int(m.group(3), 16), int(m.group(4))))
    return res


def moved_path(out):
    return os.path.join(os.path.dirname(out), "port_rdram_moved.txt")


def script(out, objects):
    objs = [o for arg in objects for o in arg.split(";") if o]
    n64_sizes = {}
    n64 = n64_symbols(n64_sizes)
    place = []
    for obj in objs:
        for sec, size, align in sections(obj):
            m = re.match(r"^\.(?:data|bss|rodata)\.(.+)$", sec)
            if not m:
                continue
            name = m.group(1)
            if name not in n64:
                continue
            addr = n64[name]
            if not (RDRAM <= addr < RDRAM_END):
                continue
            place.append((addr, obj, sec, name, size, align))
    place.sort()
    moved = []
    # a variable bigger than its room on the N64 goes wherever the host
    # linker puts it; the translated code finds it through SYM() all the
    # same.  In the LP64 build that is one of the C's the host lays out
    # bigger (or aligns where the N64 address isn't); in every build, the
    # engine's arrays with more room than the N64's (asm2c.py's GROWN).
    # (in the LP64 build a symbol's N64 size isn't always the object's: up
    # to the next sized N64 symbol is its room; elsewhere a variable of the
    # C's may run over the N64 names after it, as its #ifdef TARGET_PC has
    # it: 1D990.c's D_80367BDC)
    # (and never past the next variable placed: a data island's labels have
    # no size)
    sized = sorted(set(n64[k] for k, v in n64_sizes.items() if v and k in n64)) + [RDRAM_END]
    placed = sorted(set(p[0] for p in place)) + [RDRAM_END]
    keep = []
    for p in place:
        room = RDRAM_END
        if LP64:
            room = max(n64_sizes.get(p[3], 0), next(a for a in sized if a > p[0]) - p[0])
        room = min(room, next(a for a in placed if a > p[0]) - p[0])
        grew = p[4] > room or (LP64 and p[0] % max(p[5], 1))
        (moved if grew else keep).append(p + (room,))
    place = keep
    with open(moved_path(out), "w") as f:
        for p in moved:     # name, N64 address, host size, its room on the N64
            f.write(f"{p[3]} {p[0]:08X} {p[4]:#x} {p[6]:#x}\n")
    with open(out, "w") as f:
        f.write("/* Generated by port/tools/gen_ld.py: the game's data at its N64 addresses. */\n")
        f.write("SECTIONS\n{\n")
        f.write(f"  .rdram 0x{RDRAM:08X} : {{\n")
        f.write("    __rdram_start = .;\n")
        prev = None
        for addr, obj, sec, name, *_ in place:
            if prev and prev[0] == addr:
                sys.exit(f"gen_ld.py: {name} and {prev[3]} both at {addr:08X}")
            pat = "*" + "/".join(obj.split("/")[-2:])
            f.write(f"    . = 0x{addr - RDRAM:X}; {pat}({sec})\n")
            prev = (addr, obj, sec, name)
        f.write(f"    . = 0x{RDRAM_END - RDRAM:X};\n")
        f.write("  }\n")
        f.write("  /* the rest of the image follows its headers at 0x80400000 */\n")
        f.write("  . = 0x80410000;\n")
        f.write("}\nINSERT BEFORE .init;\n")
        # what's left of the game's .rodata (string literals, constants the
        # N64 doesn't name) goes with the data: on the N64 it's RAM like the
        # rest, and the game writes into some ("0 OF THE OTHERS", 53220.c)
        f.write("/* the game's other .rodata, writable as on the N64 */\n")
        f.write("SECTIONS\n{\n")
        # (the movable build's arena link has the N64 side in one object)
        merged = "".join(f" *gen/{os.path.basename(o)}(.rodata .rodata.*)" for o in objs if o.endswith("/n64.o"))
        f.write("  .n64_rodata : { *src/hd_code/*(.rodata .rodata.*) *src/hd_front_end/*(.rodata .rodata.*)"
                + merged + " }\n")
        f.write("}\nINSERT AFTER .data;\n")
    print(f"gen_ld.py: {len(place)} sections placed" + (f", {len(moved)} moved (bigger than on the N64)" if moved else ""))


def check(exe):
    n64 = n64_symbols()
    moved = set()
    mp = moved_path(os.path.join(os.path.dirname(os.path.abspath(exe)), "gen", "x"))
    if os.path.exists(mp):
        moved = set(l.split()[0] for l in open(mp))
    out = subprocess.run(["nm", exe], capture_output=True, text=True, check=True).stdout
    bad = 0
    total = 0
    for line in out.splitlines():
        p = line.split()
        if len(p) != 3 or p[1] in "UwTt":
            continue
        name, addr = p[2], int(p[0], 16)
        if name in moved:
            continue
        if name in n64 and RDRAM <= n64[name] < RDRAM_END and RDRAM <= addr < RDRAM_END:
            total += 1
            if addr != n64[name]:
                bad += 1
                if bad < 20:
                    print(f"  {name}: {addr:08X}, N64 {n64[name]:08X}")
    print(f"gen_ld.py check: {total} symbols in RDRAM, {bad} misplaced")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    if sys.argv[1] == "script":
        script(sys.argv[2], sys.argv[3:])
    elif sys.argv[1] == "check":
        check(sys.argv[2])
    else:
        sys.exit(__doc__)
