#!/usr/bin/env python3
"""Place the game's data at its N64 addresses.

  gen_ld.py script OUT.ld OBJECT...    the linker script
  gen_ld.py check EXE                  after the link: every game data
                                       symbol at its N64 address?

The decompiled C (and the handwritten code) rely on the layout of the
data: a struct read past the end of one variable into the next, fixed
RDRAM addresses, the heap starting where hd_code's .bss ends.  So the port
keeps every variable where the N64 has it.  The game's C is built with
-fdata-sections (one section per variable, `.data.NAME`, `.bss.NAME`), and
asm2x86.py puts each data file in one section named after its first label
(`.n64.NAME`, `.n64b.NAME`).  The script puts all of them in one output
section, `.rdram`, at 0x80000000, each at its symbol's address in the N64
link; the section is the 4 MB of RDRAM, so it also replaces a separate
arena.  Sections of variables with no N64 symbol (literals, statics the
N64 build doesn't name, the port's own data) go wherever the host linker
puts them.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
BLAST = os.path.join(ROOT, "blastcorps")
# the version of the stage-2 build the port is made from (CMake sets it)
VERSION = os.environ.get("PORT_VERSION", "us.v11")
RDRAM = 0x80000000
RDRAM_END = 0x80400000


def n64_symbols():
    addrs = {}
    for m in ("hd_code", "hd_front_end"):
        elf = os.path.join(BLAST, "build", f"{m}.{VERSION}.elf")
        out = subprocess.run(["mips-linux-gnu-nm", elf], capture_output=True, text=True, check=True).stdout
        for line in out.splitlines():
            p = line.split()
            if len(p) == 3 and not p[2].startswith((".L", "$")):
                addrs.setdefault(p[2], int(p[0], 16))
    return addrs


SEC_RE = re.compile(r"^\s*\[\s*\d+\]\s+(\S+)\s+(PROGBITS|NOBITS)\s+\S+\s+\S+\s+([0-9a-f]+)")


def sections(obj):
    out = subprocess.run(["readelf", "-SW", obj], capture_output=True, text=True, check=True).stdout
    res = []
    for line in out.splitlines():
        m = SEC_RE.match(line)
        if m and int(m.group(3), 16) > 0:
            res.append(m.group(1))
    return res


def script(out, objects):
    objs = [o for arg in objects for o in arg.split(";") if o]
    n64 = n64_symbols()
    place = []
    for obj in objs:
        for sec in sections(obj):
            m = re.match(r"^\.(?:data|bss|rodata|n64|n64b)\.(.+)$", sec)
            if not m:
                continue
            name = m.group(1)
            if name not in n64:
                continue
            addr = n64[name]
            if not (RDRAM <= addr < RDRAM_END):
                continue
            place.append((addr, obj, sec, name))
    place.sort()
    with open(out, "w") as f:
        f.write("/* Generated by port/tools/gen_ld.py: the game's data at its N64 addresses. */\n")
        f.write("SECTIONS\n{\n")
        f.write(f"  .rdram 0x{RDRAM:08X} : {{\n")
        f.write("    __rdram_start = .;\n")
        prev = None
        for addr, obj, sec, name in place:
            if prev and prev[0] == addr:
                sys.exit(f"gen_ld.py: {name} and {prev[3]} both at {addr:08X}")
            pat = "*" + "/".join(obj.split("/")[-2:])
            f.write(f"    . = 0x{addr - RDRAM:X}; {pat}({sec})\n")
            prev = (addr, obj, sec, name)
        f.write(f"    . = 0x{RDRAM_END - RDRAM:X};\n")
        f.write("  }\n")
        f.write("  /* the rest of the image follows its headers at 0x80400000 */\n")
        f.write("  . = 0x80410000;\n")
        f.write("}\nINSERT BEFORE .init;\n")
    print(f"gen_ld.py: {len(place)} sections placed")


def check(exe):
    n64 = n64_symbols()
    out = subprocess.run(["nm", exe], capture_output=True, text=True, check=True).stdout
    bad = 0
    total = 0
    for line in out.splitlines():
        p = line.split()
        if len(p) != 3 or p[1] in "UwTt":
            continue
        name, addr = p[2], int(p[0], 16)
        if name in n64 and RDRAM <= n64[name] < RDRAM_END and RDRAM <= addr < RDRAM_END:
            total += 1
            if addr != n64[name]:
                bad += 1
                if bad < 20:
                    print(f"  {name}: {addr:08X}, N64 {n64[name]:08X}")
    print(f"gen_ld.py check: {total} symbols in RDRAM, {bad} misplaced")
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    if sys.argv[1] == "script":
        script(sys.argv[2], sys.argv[3:])
    elif sys.argv[1] == "check":
        check(sys.argv[2])
    else:
        sys.exit(__doc__)
