#!/usr/bin/env python3
"""Generate blastcorps/symbol_addrs.<module>.<version>.txt.

Each file gets, below a marker line:

  * libultra names found in that module by tools/libmatch.py, tagged with how
    they were found: `lib:exact` (the body matches a reference object),
    `lib:fuzzy` (it differs by a few instructions), `lib:ref` (a matched
    function calls or references it by that name);
  * names from blastcorps/symbols_known.txt (identified by hand, given at their
    us.v11 addresses in any module) on every copy of that code, with the
    globals each copy uses, tagged as in that file;
  * names from the other modules for addresses outside this one, so a call from
    hd_front_end into hd_code gets hd_code's name, unless that name is also
    defined here (each module is linked on its own and has its own copies of
    some libultra functions);
  * `func_XXXXXXXX` (us.v11's name for it, see tools/vermap.py) for every
    call target splat would not start a function at
    on its own: it only ends one at a `jr $ra`, and not even there when a branch
    spans that return.  Without these it folds such functions into their
    predecessor.

Everything else keeps splat's default address-based name.  Lines above the
marker are kept as they are, for names given by hand.

Usage:
  gen_symbols.py <version> <objdir> [<objdir> ...]   # see tools/build_ultralib.sh
"""
import argparse
import re
import struct
from pathlib import Path

import libmatch
import vermap

CODE = libmatch.CODE
MARKER = "// ---- generated by tools/gen_symbols.py below this line; edits there are lost ----"
KNOWN = CODE / "symbols_known.txt"
KNOWN_VERSION = "us.v11"


def layout(mod, version):
    """vram, text words, and the [start, end) byte ranges of the bins in .text."""
    yml = (CODE / f"{mod}.{version}.yaml").read_text()
    vram = int(re.search(r"vram:\s*(0x[0-9A-Fa-f]+)", yml)[1], 16)
    subs = [(int(o, 16), t) for o, t in re.findall(r"- \[(0x[0-9A-Fa-f]+),\s*(\.?\w+)", yml)]
    # .text ends at the first data subsegment (a `linker` entry in hd_code and
    # hd_front_end; data/rodata ones, or a trailing bin, in init).
    end = next((o for o, t in subs if t.lstrip(".") in ("linker", "data", "rodata", "bss")), None)
    if end is None:
        end = next(o for o, t in reversed(subs) if t == "bin")
    bins = [(o, subs[i + 1][0] if i + 1 < len(subs) else end)
            for i, (o, t) in enumerate(subs) if t == "bin" and o < end]
    blob = (CODE / f"{mod}.{version}.bin").read_bytes()[:end]
    return vram, struct.unpack(f">{len(blob) // 4}I", blob), bins


def return_before(words, i):
    """Index of the return that word i follows (past its delay slot and any
    padding), or None if i does not directly follow one."""
    while True:
        if i < 2:
            return -1
        if words[i - 2] in (0x03E00008, 0x42000018):  # jr $ra / eret
            return i - 2
        if words[i - 1] != 0:
            return None
        i -= 1


def branch_spans(words, bins):
    """(lo, hi) word indices spanned by each PC-relative branch outside the bins."""
    for i, w in enumerate(words):
        if any(a <= 4 * i < e for a, e in bins):
            continue
        op, rs, rt = w >> 26, (w >> 21) & 31, (w >> 16) & 31
        if op in (4, 5, 6, 7, 0x14, 0x15, 0x16, 0x17) or \
                (op == 1 and rt in (0, 1, 2, 3, 0x10, 0x11, 0x12, 0x13)) or (op == 0x11 and rs == 8):
            off = w & 0xFFFF
            yield tuple(sorted((i, i + 1 + (off - 0x10000 if off & 0x8000 else off))))


# addiu, lb, lh, lw, lbu, lhu, sb, sh, sw, lwc1, ldc1, ld, swc1, sdc1, sd
LO_OPS = {0x09, 0x20, 0x21, 0x23, 0x24, 0x25, 0x28, 0x29, 0x2B, 0x31, 0x35, 0x37, 0x39, 0x3D, 0x3F}


def references(vram, words, bins):
    """Addresses the code calls (jal) or builds with a lui/lo pair."""
    refs = set()
    code = [not any(a <= 4 * i < e for a, e in bins) for i in range(len(words))]
    for i, w in enumerate(words):
        if not code[i]:
            continue
        op = w >> 26
        if op == 3:
            refs.add((vram & 0xF0000000) | ((w & 0x3FFFFFF) << 2))
        elif op == 0x0F:  # lui
            reg, hi = (w >> 16) & 31, w & 0xFFFF
            for j in range(i + 1, min(i + 16, len(words))):
                x = words[j]
                if x >> 26 == 0x0F and (x >> 16) & 31 == reg:
                    break
                if x >> 26 in LO_OPS and (x >> 21) & 31 == reg:
                    lo = x & 0xFFFF
                    refs.add(((hi << 16) + (lo - 0x10000 if lo & 0x8000 else lo)) & 0xFFFFFFFF)
    return refs


def parse_symbols(path):
    """[(name, addr, kind, tag)] from a symbol_addrs-style file."""
    out = []
    for line in path.read_text().splitlines():
        m = re.match(r"\s*(\w+)\s*=\s*(0x[0-9A-Fa-f]+);\s*//\s*type:(\w+)\s*(.*)", line)
        if m:
            out.append((m[1], int(m[2], 16), m[3], m[4].strip()))
    return out


def mask(w):
    """Blank what the linker fills in: jump targets and 16-bit immediates of the
    instructions that build or use addresses."""
    op = w >> 26
    if op in (2, 3):
        return w & 0xFC000000
    if op in (0x0F,) or op in LO_OPS:
        return w & 0xFFFF0000
    return w


def lo_pairs(words):
    """(index of lo instruction, address) for each lui/lo pair in `words`."""
    for i, w in enumerate(words):
        if w >> 26 != 0x0F:
            continue
        reg, hi = (w >> 16) & 31, w & 0xFFFF
        for j in range(i + 1, min(i + 16, len(words))):
            x = words[j]
            if x >> 26 == 0x0F and (x >> 16) & 31 == reg:
                break
            if x >> 26 in LO_OPS and (x >> 21) & 31 == reg:
                lo = x & 0xFFFF
                yield j, ((hi << 16) + (lo - 0x10000 if lo & 0x8000 else lo)) & 0xFFFFFFFF


def known_copies(ref, target):
    """Carry the names of symbols_known.txt over to every copy of their code.

    `ref` and `target` are {module: (vram, words, bins)} for the reference and
    the version being generated.  Returns {module: {addr: (name, kind, tag)}}."""
    known = parse_symbols(KNOWN)
    data = {a: (n, t) for n, a, k, t in known if k != "func"}
    # A known function is identified in whichever module its address falls in
    # (the modules' ranges don't overlap), then found in every other copy.
    by_mod = {}
    for n, a, k, t in known:
        if k != "func":
            continue
        rmod = next(m for m, (vram, words, _) in ref.items() if vram <= a < vram + 4 * len(words))
        by_mod.setdefault(rmod, []).append((a, n, t))
    out = {m: {} for m in target}
    for rmod, funcs in by_mod.items():
        _copy_known(ref[rmod], rmod, sorted(funcs), data, target, out)
    return out


def _copy_known(refmod, rmod, funcs, data, target, out):
    rvram, rwords, _ = refmod
    starts = sorted({a for a, _, _ in funcs} |
                    {rvram + 4 * i for i in libmatch.func_starts(libmatch.Module(rmod, rvram, rwords))})
    for addr, name, tg in funcs:
        end = next(x for x in starts if x > addr)
        body = list(rwords[(addr - rvram) // 4:(end - rvram) // 4])
        while body and body[-1] == 0:
            body.pop()
        sig = [mask(w) for w in body]
        for m, (vram, words, bins) in target.items():
            hits = [i for i in range(len(words) - len(sig) + 1)
                    if mask(words[i]) == sig[0] and [mask(w) for w in words[i:i + len(sig)]] == sig
                    and not any(a <= 4 * i < e for a, e in bins)]
            if len(hits) != 1:
                continue
            base = hits[0]
            out[m][vram + 4 * base] = (name, "func", tg)
            # The copy's globals sit where the reference's do, pair for pair.
            copy = words[base:base + len(sig)]
            theirs = dict(lo_pairs(copy))
            for j, raddr in lo_pairs(body):
                if raddr in data and j in theirs:
                    dname, dtag = data[raddr]
                    out[m].setdefault(theirs[j], (dname, "data", dtag))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("version")
    ap.add_argument("objdirs", nargs="+", type=Path)
    args = ap.parse_args()
    ver = args.version

    vm = vermap.load(ver)  # us.v11's names in the other versions
    lib, _ = libmatch.match_version(ver, args.objdirs)
    mods = {m: layout(m, ver) for m in libmatch.MODULES}
    ref = mods if ver == KNOWN_VERSION else {m: layout(m, KNOWN_VERSION) for m in libmatch.MODULES}
    copies = known_copies(ref, mods)

    def owner(addr):
        for m, (vram, words, _) in mods.items():
            if vram <= addr < vram + 4 * len(words):
                return m
        return None

    # A known function this version changed (no copy of its code) is still
    # the same function where the version map puts it.
    # (Only names us.v11 has: an ambiguous one stays unnamed there too.)
    if ver != KNOWN_VERSION:
        placed = {n for m in copies for n, _, _ in copies[m].values()}
        in_ref = {n for m in known_copies(ref, ref).values() for n, _, _ in m.values()}
        for n, a, k, t in parse_symbols(KNOWN):
            x = vm.to_target(a)
            if n in placed or n not in in_ref or x is None or owner(x) is None:
                continue
            copies[owner(x)].setdefault(x, (n, k, t + " (tools/vermap.py)"))

    # Call targets that splat's linear scan cannot see as function starts.
    spans = {m: list(branch_spans(words, bins)) for m, (_, words, bins) in mods.items()}
    hidden = {m: set() for m in mods}
    for m, (vram, words, bins) in mods.items():
        for i, w in enumerate(words):
            if w >> 26 != 3 or any(a <= 4 * i < e for a, e in bins):
                continue
            tgt = (vram & 0xF0000000) | ((w & 0x3FFFFFF) << 2)
            om = owner(tgt)
            if om is None:
                continue
            ovram, owords, obins = mods[om]
            j = (tgt - ovram) // 4
            if any(a <= 4 * j < e for a, e in obins):
                continue
            r = return_before(owords, j)
            # Splat also refuses to end a function at a return that any branch
            # in the same stretch of code spans.
            if r is None or any(lo < r <= hi or lo <= r < hi for lo, hi in spans[om]):
                hidden[om].add(tgt)

    def tag(ev):
        if any(e.startswith("fuzzy") for e in ev):
            return "lib:fuzzy"
        return "lib:exact" if any("match" in e for e in ev) else "lib:ref"

    for m in mods:
        path = CODE / f"symbol_addrs.{m}.{ver}.txt"
        manual = []
        if path.exists():
            text = path.read_text().splitlines()
            manual = text[:text.index(MARKER)] if MARKER in text else text
        taken_names = {l.split("=")[0].strip() for l in manual if "=" in l and not l.lstrip().startswith("//")}
        taken_addrs = {int(l.split("=")[1].split(";")[0], 0) for l in manual
                       if "=" in l and not l.lstrip().startswith("//")}

        own = {addr: (name, kind, tag(ev)) for addr, name, kind, ev in lib[m]}
        for addr, v in copies[m].items():
            own.setdefault(addr, v)
        names = {n for n, _, _ in own.values()}
        # Other modules' names, for addresses that are not this module's own.
        foreign, seen = {}, {}
        used = references(*mods[m])
        for om in mods:
            if om == m:
                continue
            # libmatch's names and the hand-identified ones (symbols_known.txt)
            theirs = [(addr, name, kind) for addr, name, kind, ev in lib[om]]
            theirs += [(addr, name, kind) for addr, (name, kind, why) in copies[om].items()
                       if kind == "func"]
            for addr, name, kind in theirs:
                if addr in own or name in names or owner(addr) == m or addr not in used:
                    continue
                seen.setdefault(name, set()).add(addr)
                foreign[addr] = (name, kind, f"from:{om}")
        foreign = {a: v for a, v in foreign.items() if len(seen[v[0]]) == 1}

        entries = {**foreign, **own}
        for addr in hidden[m]:
            entries.setdefault(addr, (vm.name("func", addr, True), "func", "called"))

        out = manual + [MARKER]
        for addr in sorted(entries):
            name, kind, why = entries[addr]
            if name in taken_names or addr in taken_addrs:
                continue
            out.append(f"{name} = 0x{addr:08X}; // type:{kind} {why}")
        path.write_text("\n".join(out) + "\n")
        print(f"{path.name}: {len(own)} own, {len(foreign)} foreign, {len(hidden[m])} hidden starts")


if __name__ == "__main__":
    main()
