#!/usr/bin/env python3
"""The top-level ROM layout, with every piece at its built size.

  rom_syms.py <version> --out <rom.ld> [--fixed-only] [--assets DIR]
              [--module name=path ...] [--ld-in <splat.ld> --ld-out <ld>]

The header and boot code are where the top-level config
(blastcorps.<version>.yaml) puts them.  From init on, each segment follows
the one before: init and the assets take the size of their built file
(DIR/<name>.bin, default build/assets, from tools/assets.py, which pads each
one out to where the next starts), a module the size of its gzip file
(--module, else assets/<name>.bin), the unnamed zero-padding bins between
the modules become alignment to 16, and the trailer starts where the last
module's padding ends.  For the original assets and modules that reproduces
the config's offsets.

--out gets `<segment>_ROM_START`/`_ROM_END` for every named segment, with the
original start in a comment (tools/link_syms.py matches on that; the
version dropped from module names: `hd_code_text_ROM_START`), for the stage-2
links (tools/link_syms.py --rom).  --fixed-only leaves out what depends on the
modules' sizes, for hd_code and hd_front_end, which reach only assets.  A few
addresses that aren't a segment's start get a symbol of their own (EXTRA).

--ld-in/--ld-out rewrite the top-level linker script with those positions,
without the padding bins (objcopy fills the gaps with zeros).
"""
import argparse
import re
import sys
from pathlib import Path

import yaml

MODULES = ("hd_code_text", "hd_code_data", "hd_front_end_text", "hd_front_end_data")
FIRST_CHAINED = "init."   # init, then the texture table right after it

# Addresses the code uses that aren't a segment's start: {segment: [(name,
# offset from its start)]}.  func_80255DC8 (hd_code 00000.c) DMAs 0xC0 bytes
# from static_data, its inflated size, which runs past the data's end.
EXTRA = {"static_data": [("DMA_END", 0xC0)]}


def cname(s):
    s = re.sub(r"[^0-9a-zA-Z_]", "_", s)
    return "_" + s if s[0].isdigit() else s


def layout(ver, sizes, assets=Path("build/assets")):
    """[(name or None, start, end, kind, original start)] in ROM order; kind
    is 'fixed', 'asset', 'module', 'pad' or 'after' (placed after a module)."""
    cfg = yaml.safe_load(Path(f"blastcorps.{ver}.yaml").read_text())
    segs = []
    for s in cfg["segments"]:
        if isinstance(s, dict):
            segs.append((s.get("name"), s["start"]))
        elif len(s) >= 3:
            segs.append((s[2], s[0]))
        else:
            segs.append((None, s[0]))
    out = []
    moved = False
    chained = False
    pos = None
    for k, (name, start) in enumerate(segs[:-1]):
        end = segs[k + 1][1]
        base = name.rsplit(f".{ver}", 1)[0] if name else None
        if name and name.startswith(FIRST_CHAINED):
            chained = True
            pos = start
        if base in MODULES:
            moved = True
            size = sizes.get(base, end - start)
            start = pos if pos is not None else start
            out.append((base, start, start + size, "module", segs[k][1]))
            pos = start + size
        elif not chained:
            out.append((name, start, end, "fixed", start))
        elif name is None:
            new = (pos + 15) & ~15
            out.append((None, pos, new, "pad", start))
            pos = new
        else:
            built = assets / f"{name}.bin"
            size = built.stat().st_size if built.exists() else end - start
            out.append((name, pos, pos + size, "after" if moved else "asset", start))
            pos += size
    # The last segment (the 0xFF trailer) still ends where the ROM did.
    name, start, end, kind, orig = out[-1]
    if kind == "after" and end < segs[-1][1]:
        out[-1] = (name, start, segs[-1][1], kind, orig)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("version")
    ap.add_argument("--out", required=True)
    ap.add_argument("--fixed-only", action="store_true")
    ap.add_argument("--module", action="append", default=[], metavar="NAME=PATH")
    ap.add_argument("--assets", default="build/assets")
    ap.add_argument("--ld-in")
    ap.add_argument("--ld-out")
    args = ap.parse_args()

    ver = args.version
    paths = {m: Path(f"assets/{m}.{ver}.bin") for m in MODULES}
    for spec in args.module:
        name, _, path = spec.partition("=")
        paths[name] = Path(path)
    sizes = {} if args.fixed_only else {m: p.stat().st_size for m, p in paths.items()}
    segs = layout(ver, sizes, Path(args.assets))

    lines = [f"/* generated by tools/rom_syms.py from blastcorps.{ver}.yaml */"]
    for name, start, end, kind, orig in segs:
        if name is None or (args.fixed_only and kind not in ("fixed", "asset")):
            continue
        lines += [f"{cname(name)}_ROM_START = 0x{start:X}; /* originally 0x{orig:X} */",
                  f"{cname(name)}_ROM_END = 0x{end:X};"]
        for sym, off in EXTRA.get(name, []):
            lines.append(f"{cname(name)}_{sym} = 0x{start + off:X}; /* originally 0x{orig + off:X} */")
    Path(args.out).write_text("\n".join(lines) + "\n")

    if args.ld_in:
        text = Path(args.ld_in).read_text()
        for name, start, end, kind, orig in segs:
            if kind == "fixed":
                continue
            if kind == "module":
                sect = cname(f"{name}.{ver}")
            else:
                sect = cname(name) if name else f"_{orig:X}"
            n = 0
            text, k = re.subn(rf"(\n    __romPos = )0x[0-9A-F]+(;\n    \. = __romPos;\n    {sect}_ROM_START = )",
                              rf"\g<1>0x{start:X}\2", text)
            n += k
            text, k = re.subn(rf"(\n    {sect}_ROM_END = )0x[0-9A-F]+(;\n    __romPos = )0x[0-9A-F]+;",
                              rf"\g<1>0x{end:X}\g<2>0x{end:X};", text)
            n += k
            if n != 2:
                sys.exit(f"{args.ld_in}: can't place {sect}")
            if kind == "pad":
                # objcopy fills the gap with zeros
                text = text.replace(f"\n        build/assets/{orig:X}.bin.o(.data);", "")
            built = Path(args.assets) / f"{name}.bin"
            size = (built if built.exists() else Path(f"assets/{name}.bin")).stat().st_size if kind == "after" else None
            if size is not None and end - start > size:
                # the trailer is all 0xFF; a smaller build fills it out
                line = f"\n        build/assets/{name}.bin.o(.data);"
                text = text.replace(line, line + f"\n        FILL(0xFFFFFFFF);\n        . += 0x{end - start - size:X};")
        Path(args.ld_out).write_text(text)


main()
